services:
    steamidp:
        image: neothor/steam-openid-connect-provider:develop
        build: ./src
        environment: 
            OpenID__ClientID: keycloak
            OpenID__ClientName: keycloak
            OpenId__ClientSecret: keycloak
            OpenID__RedirectUri: https://dev.local/auth/realms/dev/broker/steam/endpoint
            Hosting__BasePath: /steam