services:
    steam-openid-connect-provider:
        stdin_open: true
        tty: true
        environment:
            - OpenID__RedirectUri=https://ebateam-steamauth.f6dnvr.easypanel.host/auth/realms/master/broker/steam/endpoint
            - OpenID__ClientID=steamidp
            - OpenID__ClientSecret=mysecret
            - OpenID__ClientName=myclientname
            - Steam__ApplicationKey=MySteamApiKey
        restart: unless-stopped
        container_name: steamidp
        image: ghcr.io/byo-software/steam-openid-connect-provider
