services:
    steam-openid-connect-provider:
        environment:
           # - OpenID__RedirectUri=steam-openid-connect-provider/auth/realms/master/broker/steam/endpoint 
            - OpenID__ClientID=steamidp
            - OpenID__ClientSecret=mysecret
            - OpenID__ClientName=myclientname
            - Steam__ApplicationKey=MySteamApiKey
        restart: unless-stopped
        image: ghcr.io/byo-software/steam-openid-connect-provider