services:
    steam-openid-connect-provider:
        environment:
            - OpenID__RedirectUri=https://ebateam-logto.f6dnvr.easypanel.host/callback/emgl690ja9gronnqh70ek
            - OpenID__ClientID=steamidp
            - OpenID__ClientSecret=mysecret
            - OpenID__ClientName=myclientname
            - Steam__ApplicationKey=MySteamApiKey
        restart: unless-stopped
        image: ghcr.io/byo-software/steam-openid-connect-provider